import imageProjet1 from "../../IMAGES/encours.png";
import portofolio from "../../IMAGES/portofolio.png";
import greenasso from "../../IMAGES/GreenReso Project.png";
import chup from "../../IMAGES/chu.png";

export const projetsData = {
  fr: [
    {
      num: "01",
      title: "Cloud Healthcare Unit – Data Warehouse & Big Data",
      category: "Data Engineering & Big Data",
      image: chup,
      year: "2026",
      type: "Projet académique",
      duration: "3 mois",
      shortDesc: "Conception d'un système décisionnel de santé permettant d'intégrer, structurer et analyser des données médicales issues de sources hétérogènes.",
      context: "Le groupe CHU souhaitait exploiter les nombreuses données générées par ses systèmes de gestion médicale et ses sources FTP afin d'améliorer le suivi des patients, des hospitalisations, des décès et de la satisfaction. Le principal enjeu était d'intégrer des données hétérogènes et historiques dans une architecture permettant leur analyse et leur visualisation.",
      solution: "SOURCES DE DONNÉES ➔ EXTRACTION & INTÉGRATION ➔ MODÉLISATION DU DATA WAREHOUSE ➔ STOCKAGE ➔ OPTIMISATION DES DONNÉES ➔ REQUÊTES ANALYTIQUES ➔ DASHBOARD & STORYTELLING",
      features: [
        "Analyse des besoins des utilisateurs",
        "Étude de l'architecture Big Data à mettre en place",
        "Modélisation conceptuelle des données",
        "Conception du Data Warehouse",
        "Intégration de données provenant de PostgreSQL, fichiers CSV et fichiers plats",
        "Développement de jobs d'alimentation du schéma décisionnel",
        "Création et chargement des tables",
        "Vérification et interrogation des données",
        "Partitionnement et utilisation de buckets",
        "Mesure et optimisation des performances des requêtes",
        "Création de visualisations et d'un dashboard",
        "Restitution des résultats sous forme de storytelling"
      ],
      results: "Mise en place d'une solution décisionnelle permettant de centraliser des données de santé provenant de plusieurs sources et de produire des analyses sur les consultations, hospitalisations, diagnostics, décès et satisfaction des patients.",
      technologies: ["Python", "PostgreSQL", "Talend", "Jupyter Notebook", "Data Warehouse", "Big Data", "SQL", "ETL", "Modélisation dimensionnelle", "Power BI"],
      href: "https://github.com/MariamaFofana"
    },
    {
      num: "02",
      title: "IA for HumanForYou – Prédiction de l'attrition",
      category: "Intelligence Artificielle & Machine Learning",
      image: imageProjet1,
      year: "2026",
      type: "Projet académique",
      duration: "Projet académique",
      shortDesc: "Analyse de données RH et développement de modèles de Machine Learning pour identifier les facteurs associés au départ des employés et prédire le risque d'attrition.",
      context: "HumanForYou, une entreprise pharmaceutique de 4 000 collaborateurs, fait face à un taux de turnover annuel d'environ 15 %. L'objectif du projet était d'analyser les données des employés afin d'identifier les facteurs influençant l'attrition et de proposer des modèles permettant d'identifier les situations à risque.",
      solution: "DONNÉES RH ➔ PRÉPARATION & NETTOYAGE ➔ ANALYSE EXPLORATOIRE ➔ SÉLECTION DES VARIABLES ➔ MODÈLES DE MACHINE LEARNING ➔ ÉVALUATION ➔ AMÉLIORATION DU MODÈLE ➔ INTERPRÉTATION & RECOMMANDATIONS",
      features: [
        "Analyse et préparation des données RH",
        "Exploration des facteurs liés à l'attrition",
        "Traitement des données issues de fichiers CSV",
        "Analyse des variables professionnelles et personnelles",
        "Sélection et préparation des variables pour le Machine Learning",
        "Entraînement de plusieurs modèles de classification",
        "Évaluation des modèles à l'aide de métriques",
        "Amélioration du modèle sélectionné",
        "Interprétation des résultats",
        "Formulation de recommandations pour limiter le turnover",
        "Prise en compte des enjeux éthiques liés à l'utilisation de l'IA"
      ],
      results: "Développement d'une démarche de Machine Learning permettant d'analyser les facteurs associés à l'attrition et d'évaluer différents modèles afin d'identifier une approche adaptée aux besoins de l'entreprise.",
      technologies: ["Python", "Jupyter Notebook", "Pandas", "NumPy", "Scikit-learn", "Machine Learning", "Classification", "Data Analysis", "Visualisation de données"],
      href: "https://github.com/MariamaFofana/MonPortofolio"
    },
    {
      num: "03",
      title: "EasySave – Logiciel de sauvegarde",
      category: "Développement logiciel",
      image: imageProjet1,
      year: "2026",
      type: "Projet académique",
      duration: "Projet évolutif",
      shortDesc: "Conception et évolution d'une solution de sauvegarde de fichiers en C#/.NET, intégrant gestion des jobs, journalisation, interface graphique, chiffrement et centralisation des logs.",
      context: "Dans le cadre d'un projet pour l'éditeur ProSoft, nous avons développé EasySave, un logiciel permettant de créer et d'exécuter des tâches de sauvegarde. Le projet a évolué à travers plusieurs versions afin d'intégrer progressivement de nouvelles fonctionnalités et de répondre aux besoins des utilisateurs.",
      solution: "CONFIGURATION DES JOBS ➔ SAUVEGARDE ➔ JOURNALISATION ➔ SUIVI EN TEMPS RÉEL ➔ INTERFACE GRAPHIQUE ➔ CHIFFREMENT ➔ SAUVEGARDES PARALLÈLES ➔ CENTRALISATION DES LOGS",
      results: "Développement progressif d'une solution de sauvegarde évolutive permettant de gérer les tâches de sauvegarde, suivre leur progression, journaliser les opérations et centraliser les logs.",
      technologies: ["C#", ".NET 8", "WPF", "MVVM", "Git/GitHub", "UML", "JSON", "Docker"],
      href: "https://github.com/MariamaFofana"
    },
    {
      num: "04",
      title: "GreenReso – Conception & Sécurisation du SI",
      category: "Systèmes & Cybersécurité",
      image: greenasso,
      year: "2026",
      type: "Projet académique",
      duration: "Projet académique",
      shortDesc: "Conception et mise en œuvre d'une infrastructure informatique sécurisée avec segmentation réseau, machines virtuelles, Active Directory et gestion des accès.",
      context: "GreenReso souhaitait professionnaliser son système d'information afin de sécuriser ses données, structurer les ressources partagées et mieux contrôler les accès des utilisateurs. Le projet consistait à concevoir une infrastructure cohérente et à réaliser une maquette technique permettant de mettre en pratique les mécanismes de sécurité.",
      solution: "ANALYSE DES BESOINS ➔ SEGMENTATION DU RÉSEAU EN 3 ZONES ➔ VIRTUALISATION ➔ VM ADMINISTRATEUR & VM CLIENT ➔ ACTIVE DIRECTORY ➔ GROUPES & DROITS ➔ GPO ➔ POWERSHELL ➔ SÉCURISATION",
      features: [
        "Segmentation du réseau en trois zones",
        "Mise en place d'une VM administrateur et d'une VM client",
        "Déploiement d'Active Directory",
        "Création et organisation des utilisateurs et groupes",
        "Gestion des droits d'accès aux ressources",
        "Mise en place de stratégies GPO",
        "Automatisation avec des scripts PowerShell",
        "Création de l'arborescence des dossiers avec gestion des droits NTFS",
        "Organisation des espaces partagés",
        "Réalisation d'un support de sensibilisation à la cybersécurité",
        "Conception d'une architecture réseau sécurisée"
      ],
      results: "Réalisation d'une maquette fonctionnelle permettant de simuler l'infrastructure cible de GreenReso, avec un réseau segmenté, des machines virtuelles, une gestion centralisée des utilisateurs et des droits d'accès.",
      technologies: ["Active Directory", "Windows Server", "PowerShell", "GPO", "NTFS", "Virtualisation", "Réseaux", "Cybersécurité"],
      href: "https://github.com/MariamaFofana"
    },
    {
      num: "05",
      title: "PAD – Analyse de données Titanic",
      category: "Data Analysis",
      image: imageProjet1,
      year: "2022",
      type: "Projet personnel – Premier projet Data",
      duration: "Projet personnel",
      shortDesc: "Première mise en pratique de l'analyse de données à travers l'étude du dataset Titanic avec Python et Jupyter Notebook.",
      context: "Ce projet constitue une première expérience en analyse de données. L'objectif était de découvrir la manipulation et l'exploration d'un jeu de données à partir du dataset Titanic.",
      solution: "DATASET TITANIC ➔ IMPORTATION DES DONNÉES ➔ EXPLORATION ➔ ANALYSE ➔ VISUALISATION",
      features: [
        "Exploration du dataset Titanic",
        "Manipulation des données",
        "Analyse exploratoire",
        "Utilisation de données sous forme de dataset",
        "Création de visualisations",
        "Travail dans un notebook Jupyter"
      ],
      results: "Une première expérience pratique en analyse de données permettant de découvrir la manipulation de données et leur représentation graphique avec Python.",
      technologies: ["Python", "Jupyter Notebook", "Pandas", "NumPy", "Matplotlib"],
      href: "https://github.com/MariamaFofana/PAD"
    },
    {
      num: "06",
      title: "Portfolio personnel",
      category: "Développement Web",
      image: portofolio,
      year: "2026",
      type: "Projet personnel",
      duration: "Projet personnel",
      shortDesc: "Conception et développement d'un portfolio personnel interactif pour présenter mon parcours, mes compétences et mes projets.",
      context: "L'objectif était de créer une plateforme personnelle permettant de présenter mon parcours académique, mes expériences, mes compétences et mes réalisations dans un environnement moderne et interactif.",
      solution: "CONCEPTION UI ➔ REACT ➔ COMPOSANTS RÉUTILISABLES ➔ ANIMATIONS & INTERACTIONS ➔ NODE.JS ➔ FORMULAIRE DE CONTACT ➔ ENVOI DES E-MAILS ➔ DÉPLOIEMENT",
      features: [
        "Présentation du parcours et de la formation",
        "Présentation des expériences et associations",
        "Présentation des compétences techniques",
        "Galerie de projets avec fiches détaillées",
        "Section certifications",
        "Section loisirs",
        "Formulaire de contact",
        "Réception des messages par e-mail",
        "Interface responsive",
        "Navigation et interactions dynamiques"
      ],
      results: "Création d'un portfolio personnel interactif permettant de centraliser mon parcours et mes réalisations tout en mettant en pratique mes compétences en développement web.",
      technologies: ["React", "Node.js", "JavaScript", "HTML", "CSS", "Git", "GitHub"],
      href: "https://github.com/MariamaFofana/MonPortofolio"
    },
    {
      num: "07",
      title: "Pierre Feuille Ciseau",
      category: "Développement Web",
      image: imageProjet1,
      year: "2025",
      type: "Projet de formation – ADA School",
      duration: "5 jours",
      shortDesc: "Développement en équipe d'un jeu Pierre-Feuille-Ciseau en JavaScript avec une interface interactive en HTML/CSS.",
      context: "Dans le cadre d'une formation de cinq jours à ADA School, nous avons réalisé en équipe un jeu Pierre-Feuille-Ciseau. Le projet avait pour objectif de mettre en pratique les bases de la programmation JavaScript, la logique conditionnelle et le développement d'une interface web simple.",
      solution: "LOGIQUE DU JEU ➔ CHOIX UTILISATEUR ➔ CHOIX ALÉATOIRE DE L'ORDINATEUR ➔ COMPARAISON ➔ CALCUL DES SCORES ➔ AFFICHAGE DU RÉSULTAT",
      features: [
        "Choix de l'utilisateur via des boutons interactifs",
        "Génération aléatoire du choix de l'ordinateur",
        "Comparaison des choix",
        "Détermination du gagnant ou de l'égalité",
        "Comptabilisation des scores",
        "Affichage du choix de l'utilisateur et de l'ordinateur",
        "Interface HTML/CSS",
        "Évolution d'une première version en console vers une interface graphique"
      ],
      results: "Réalisation d'un jeu fonctionnel permettant de mettre en pratique les bases de JavaScript, HTML et CSS, ainsi que le travail collaboratif au sein d'une équipe de trois personnes.",
      technologies: ["JavaScript", "HTML", "CSS", "Git", "GitHub"],
      href: "https://github.com/MariamaFofana/PierreFeuilleCiseau"
    }
  ],
  en: [
    {
      num: "01",
      title: "Cloud Healthcare Unit – Data Warehouse & Big Data",
      category: "Data Engineering & Big Data",
      image: chup,
      year: "2026",
      type: "Academic Project",
      duration: "3 months",
      shortDesc: "Design of a healthcare decision-making system to integrate, structure, and analyze medical data from heterogeneous sources.",
      context: "The CHU group wanted to leverage the extensive data generated by its medical management systems and FTP sources to improve patient monitoring, hospitalizations, mortality rates, and satisfaction. The main challenge was integrating heterogeneous and historical data into an architecture enabling analysis and visualization.",
      solution: "DATA SOURCES ➔ EXTRACTION & INTEGRATION ➔ DATA WAREHOUSE MODELING ➔ STORAGE ➔ DATA OPTIMIZATION ➔ ANALYTIC QUERIES ➔ DASHBOARD & STORYTELLING",
      features: [
        "User requirement analysis",
        "Study of the Big Data architecture to implement",
        "Conceptual data modeling",
        "Data Warehouse design",
        "Integration of data from PostgreSQL, CSV files, and flat files",
        "Development of decision-making schema ingestion jobs",
        "Creation and loading of tables",
        "Data verification and querying",
        "Partitioning and usage of buckets",
        "Measurement and optimization of query performance",
        "Creation of visualizations and a dashboard",
        "Results presentation through storytelling"
      ],
      results: "Implementation of a decision-making solution to centralize health data from multiple sources and generate insights on consultations, hospitalizations, diagnoses, mortality, and patient satisfaction.",
      technologies: ["Python", "PostgreSQL", "Talend", "Jupyter Notebook", "Data Warehouse", "Big Data", "SQL", "ETL", "Dimensional Modeling", "Power BI"],
      href: "https://github.com/MariamaFofana"
    },
    {
      num: "02",
      title: "IA for HumanForYou – Attrition Prediction",
      category: "Artificial Intelligence & Machine Learning",
      image: imageProjet1,
      year: "2026",
      type: "Academic Project",
      duration: "Academic Project",
      shortDesc: "HR data analysis and Machine Learning model development to identify factors associated with employee turnover and predict attrition risk.",
      context: "HumanForYou, a pharmaceutical company with 4,000 employees, faces an annual turnover rate of about 15%. The project's goal was to analyze employee data to identify factors influencing attrition and propose models to flag high-risk situations.",
      solution: "HR DATA ➔ PREPARATION & CLEANING ➔ EXPLORATORY ANALYSIS ➔ FEATURE SELECTION ➔ MACHINE LEARNING MODELS ➔ EVALUATION ➔ MODEL IMPROVEMENT ➔ INTERPRETATION & RECOMMENDATIONS",
      features: [
        "HR data analysis and preparation",
        "Exploration of factors linked to attrition",
        "Processing of data from CSV files",
        "Analysis of professional and personal variables",
        "Feature selection and preparation for Machine Learning",
        "Training of multiple classification models",
        "Model evaluation using key metrics",
        "Improvement of the selected model",
        "Interpretation of results",
        "Formulation of recommendations to reduce turnover",
        "Consideration of ethical issues related to AI usage"
      ],
      results: "Development of a Machine Learning workflow to analyze attrition-related factors and evaluate various models to determine an approach tailored to corporate needs.",
      technologies: ["Python", "Jupyter Notebook", "Pandas", "NumPy", "Scikit-learn", "Machine Learning", "Classification", "Data Analysis", "Data Visualization"],
      href: "https://github.com/MariamaFofana/MonPortofolio"
    },
    {
      num: "03",
      title: "EasySave – Backup Software",
      category: "Software Development",
      image: imageProjet1,
      year: "2026",
      type: "Academic Project",
      duration: "Evolving Project",
      shortDesc: "Design and evolution of a file backup solution in C#/.NET, integrating job management, logging, graphical user interface, encryption, and centralized logs.",
      context: "As part of a project for the publisher ProSoft, we developed EasySave, software to create and run backup tasks. The project evolved through several versions to gradually incorporate new features and meet user requirements.",
      solution: "JOB CONFIGURATION ➔ BACKUP ➔ LOGGING ➔ REAL-TIME MONITORING ➔ GUI ➔ ENCRYPTION ➔ PARALLEL BACKUPS ➔ LOG CENTRALIZATION",
      results: "Progressive development of an adaptable backup solution allowing users to manage backup tasks, track progress, log operations, and centralize logs.",
      technologies: ["C#", ".NET 8", "WPF", "MVVM", "Git/GitHub", "UML", "JSON", "Docker"],
      href: "https://github.com/MariamaFofana"
    },
    {
      num: "04",
      title: "GreenReso – IS Design & Security",
      category: "Systems & Cybersecurity",
      image: greenasso,
      year: "2026",
      type: "Academic Project",
      duration: "Academic Project",
      shortDesc: "Design and implementation of a secure IT infrastructure with network segmentation, virtual machines, Active Directory, and access management.",
      context: "GreenReso wanted to professionalize its information system to secure data, structure shared resources, and better control user access. The project involved designing a coherent infrastructure and building a technical mockup to practice security mechanisms.",
      solution: "REQUIREMENTS ANALYSIS ➔ 3-ZONE NETWORK SEGMENTATION ➔ VIRTUALIZATION ➔ ADMIN & CLIENT VMS ➔ ACTIVE DIRECTORY ➔ GROUPS & RIGHTS ➔ GPO ➔ POWERSHELL ➔ SECURITY",
      features: [
        "Network segmentation into three zones",
        "Setup of an administrator VM and a client VM",
        "Deployment of Active Directory",
        "Creation and organization of users and groups",
        "Management of resource access rights",
        "Implementation of GPO policies",
        "Automation with PowerShell scripts",
        "Creation of folder directory trees with NTFS permissions",
        "Organization of shared spaces",
        "Creation of cybersecurity awareness support materials",
        "Design of a secure network architecture"
      ],
      results: "Creation of a functional mockup to simulate GreenReso's target infrastructure, featuring a segmented network, virtual machines, centralized user management, and access permissions.",
      technologies: ["Active Directory", "Windows Server", "PowerShell", "GPO", "NTFS", "Virtualization", "Networks", "Cybersecurity"],
      href: "https://github.com/MariamaFofana"
    },
    {
      num: "05",
      title: "PAD – Titanic Data Analysis",
      category: "Data Analysis",
      image: imageProjet1,
      year: "2022",
      type: "Personal Project – First Data Project",
      duration: "Personal Project",
      shortDesc: "First practical implementation of data analysis through the study of the Titanic dataset using Python and Jupyter Notebook.",
      context: "This project represents a first experience in data analysis. The objective was to discover data manipulation and exploration using the Titanic dataset.",
      solution: "TITANIC DATASET ➔ DATA IMPORT ➔ EXPLORATION ➔ ANALYSIS ➔ VISUALIZATION",
      features: [
        "Exploration of the Titanic dataset",
        "Data manipulation",
        "Exploratory analysis",
        "Dataset utilization",
        "Creation of visualizations",
        "Work within a Jupyter notebook"
      ],
      results: "A first practical experience in data analysis, discovering data manipulation and graphical representation with Python.",
      technologies: ["Python", "Jupyter Notebook", "Pandas", "NumPy", "Matplotlib"],
      href: "https://github.com/MariamaFofana/PAD"
    },
    {
      num: "06",
      title: "Personal Portfolio",
      category: "Web Development",
      image: portofolio,
      year: "2026",
      type: "Personal Project",
      duration: "Personal Project",
      shortDesc: "Design and development of an interactive personal portfolio to showcase my background, skills, and projects.",
      context: "The goal was to create a personal platform to present my academic background, experiences, skills, and achievements in a modern, interactive environment.",
      solution: "UI DESIGN ➔ REACT ➔ REUSABLE COMPONENTS ➔ ANIMATIONS & INTERACTIONS ➔ NODE.JS ➔ CONTACT FORM ➔ EMAIL SENDING ➔ DEPLOYMENT",
      features: [
        "Presentation of background and education",
        "Presentation of experiences and associations",
        "Presentation of technical skills",
        "Project gallery with detailed views",
        "Certifications section",
        "Hobbies section",
        "Contact form",
        "Email message reception",
        "Responsive interface",
        "Dynamic navigation and interactions"
      ],
      results: "Creation of an interactive personal portfolio centralizing my career path and achievements while practicing web development skills.",
      technologies: ["React", "Node.js", "JavaScript", "HTML", "CSS", "Git", "GitHub"],
      href: "https://github.com/MariamaFofana/MonPortofolio"
    },
    {
      num: "07",
      title: "Rock Paper Scissors",
      category: "Web Development",
      image: imageProjet1,
      year: "2025",
      type: "Training Project – ADA School",
      duration: "5 days",
      shortDesc: "Team development of a Rock-Paper-Scissors game in JavaScript with an interactive HTML/CSS interface.",
      context: "As part of a five-day training at ADA School, our team built a Rock-Paper-Scissors game. The project aimed to put JavaScript programming fundamentals, conditional logic, and simple web interface development into practice.",
      solution: "GAME LOGIC ➔ USER CHOICE ➔ RANDOM COMPUTER CHOICE ➔ COMPARISON ➔ SCORE CALCULATION ➔ RESULT DISPLAY",
      features: [
        "User choice via interactive buttons",
        "Random generation of computer choice",
        "Choice comparison",
        "Winner or tie determination",
        "Score tracking",
        "Display of user and computer choices",
        "HTML/CSS interface",
        "Evolution from a console-based version to a graphical interface"
      ],
      results: "Completion of a functional game applying JavaScript, HTML, and CSS fundamentals, alongside collaborative teamwork within a three-person group.",
      technologies: ["JavaScript", "HTML", "CSS", "Git", "GitHub"],
      href: "https://github.com/MariamaFofana/PierreFeuilleCiseau"
    }
  ]
};

export const categories = {
  fr: ["Tous", "Data Engineering & Big Data", "Intelligence Artificielle & Machine Learning", "Développement logiciel", "Systèmes & Cybersécurité", "Data Analysis", "Développement Web"],
  en: ["All", "Data Engineering & Big Data", "Artificial Intelligence & Machine Learning", "Software Development", "Systems & Cybersecurity", "Data Analysis", "Web Development"]
};